kafka:
  bootstrap-server: localhost:9092
  topics:
    snapshots: telemetry.snapshots.v1
    hubs: telemetry.hubs.v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer_db
    username: analyzer_user
    password: analyzer_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum.analyzer.services: DEBUG
    ru.yandex.practicum.analyzer.grpc: DEBUG